parameters:
    ###> DEFAULT ###
    
    ###> DOCTRINE ###
    grin_way_web_app.doctrine:
        pre_persist_for_created_at_event_listener:
            is_listen: true
            priority: 0
            connection: 'default'
        pre_update_for_updated_at_event_listener:
            is_listen: true
            priority: 0
            connection: 'default'
    ###< DOCTRINE ###

    ###> MESSENGER ###
    grin_way_web_app.messenger:
        buses:
            ###> BUS FOR QUERY ###
            grin_way_web_app.messenger.query.bus:
                default_middleware: false
                middleware:
                    -   id:     'add_bus_name_stamp_middleware'
                        arguments:
                        -   'grin_way_web_app.messenger.query.bus'
                    -   id:     'handle_message'
            ###< BUS FOR QUERY ###
        transports:
            grin_way_web_app.sync: 'sync://'
        routing:
            'GrinWay\WebApp\Contract\Messenger\HasSyncTransportInterface': grin_way_web_app.sync
    ###< MESSENGER ###

    ###< DEFAULT ###

services:
    _defaults:
        public:             false
        autowire:           false
        autoconfigure:      false
        
        bind:
            
            ###> VALUES ###
            ###< VALUES ###
            
            ###> SERVICES ###
            ###< SERVICES ###